### ISSUE TITLE
The highlighting breaks with Sublime 3170

### ISSUE THREAD

**Issue by bbalban** [davidrios/pug-tmbundle#22]
Apparently they introduced a lot of syntax related changes.

**Comment by omggga** [comment]
Error loading scope:source.sass: Unable to find syntax file for scope source.sass in Packages/Pug/Syntaxes/Pug.tmLanguage
Error loading scope:source.less: Unable to find syntax file for scope source.less in Packages/Pug/Syntaxes/Pug.tmLanguage

**Comment by JohnHarrison90** [comment]
Is this plugin still maintained?

**Comment by cristianl** [comment]
This is directly related to changes made to the built-in [JavaScript language package](https://github.com/sublimehq/Packages/commits/master/JavaScript/JavaScript.sublime-syntax), it's not due to changes in Core. If you disable the `JavaScript` package, highlighting of non-JS blocks works.

Temporary (hacky) workarounds: 

- If you need JS highlighting inside pug files, you can switch to another JavaScript syntax definition (e.g. Babel or an older version of the JavaScript package)
- If you'd rather keep using the official JavaScript syntax package for .js files, replace the references to `source.js` in the Pug syntax definition with another scope (can be an invalid scope like `source.jsnoop`, but you'll get `Unable to find syntax file for scope` warnings in the console).
  - Forking an older version of the JavaScript syntax package and replacing its scope with something like `source.jsforpug` and then replacing `source.js` in the Pug syntax file with `source.jsforpug` _might_ work.

**Comment by anhcao142** [comment]
My (temporary) solution is set the default syntax for pug (jade) file using `pug (python)` syntax.

<img width="936" alt="screen shot 2018-05-16 at 11 19 16 pm" src="https://user-images.githubusercontent.com/5773176/40129907-b984b00a-595f-11e8-9f98-d2f9e0da7c17.png">

**Comment by Soviut** [comment]
@cristianl 's suggestion worked. The steps are

- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>` (Tools > Command Palette)
- type `disable package`
- type `javascript`
- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>` (Tools > Command Palette)
- type `install package`
- type `babel`

**Comment by ded** [comment]
@Soviut that worked great! Thanks — One thing to note is that `.js` files get set to `Plain Text` and need to be switched to use `Set Syntax: Babel (JavaScript)` after following your steps.

**Comment by bbalban** [comment]
> @cristianl 's suggestion worked. The steps are
> 
> * Ctrl + Shift + P` (Tools > Command Palette)
> * type `disable package`
> * type `javascript`
> * Ctrl + Shift + P` (Tools > Command Palette)
> * type `install package`
> * type `babel`

thank you this saved me a lot of hassle. it worked!
