### ISSUE TITLE
The bundle doesn't show up in TextMate 2

### ISSUE THREAD

**Issue by Wolfr** [davidrios/pug-tmbundle#6]
Just wondering if other people have the same problem; the bundle doesn't show up in Textmate 2. I am using the method provided on this repo's homepage https://github.com/davidrios/pug-tmbundle .

**Comment by davidrios** [comment]
It has been quite a while since I tested with Textmate, that was when I had a Mac at my previous job. I don't own a Mac myself, so unfortunately I can't test it now.

I have found this blog post: http://blog.macromates.com/2013/2-0-status-and-faq/. They say to put the bundles in a different directory, can you check that?

**Comment by andrewminer** [comment]
I ran into this problem as well.  The best solution is to clone into whatever directory you like (e.g., `Downloads` or `Desktop`), and then just double-click the `Pug.tmbundle` "file".  This will automatically launch TextMate, and it will ask whether you'd like to install the bundle.  Say "okay" and you're done.
